### PR TITLE
BLCK website, scratch but for SPWN [using Blockly]

### PR DESCRIPTION
**Pull request by SpeckyYT**

### CODE REVIEW

**Comment by m1kadev** [comment]
blls (balls)

**Comment by itsmebombie** [comment]
tags (tags)

**Comment by itsmebombie** [comment]
😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by SpeckyYT** [comment]
cry about it noob

**Comment by itsmebombie** [comment]
😢😢😢😢😭😢😢😢😢

**Pull request closed without merging**
